#!/bin/sh
echo "Switching to branch master"
git checkout master
echo "Building app"
npm run build
echo "Deploying files to server"
rsync -avP --exclude='manifest.json' build/ appsuser@172.105.15.184:/var/www/yardsalemanager.com/
echo "Deployment complete"
